# This workflow will build a Spring project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Task-Manager CI with Maven

on:
  push:
    branches: [ issue* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11.0.9
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.9'
        java-package: jdk

    - name: print java version
      run: java -version | javac -version

    - name: print maven version
      run: mvn -version

    - name: Caching local maven repository
      uses: actions/cache@v2
      with:
         path: ~/.m2
         key: ${{ runner.os }}-maven-${{ hashFiles('taskmanager-api/pom.xml') }}
         restore-keys: ${{ runner.os }}-maven-

    - name: Test with Maven
      run: cd taskmanager-api/; pwd; mvn -B clean package
    
    - name: Echo current directory
      run: pwd;
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag taskmanager:latest

